apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: nolcore
resources:
  - namespace.yaml
  - postgres.yaml
  - api.yaml
  - ingress.yaml
configMapGenerator:
  - name: nolcore-schema
    files:
      - schema.sql=schema.sql
generatorOptions:
  disableNameSuffixHash: true
